services:
  meili:
    image: getmeili/meilisearch:v1.8
    network_mode: 'host'
    stdin_open: true
    environment:
      MEILI_ENV: development # for the gui
        # MEILI_MASTER_KEY: 'hereisalongproductionkey'
      MEILI_NO_ANALYTICS: 'no' # not sure this does anything
      MEILI_LOG_LEVEL: 'WARN'
    command: "meilisearch --no-analytics"
    volumes:
      - ./data:/meili_data
