services:
  typesense:
    image: typesense/typesense:26.0
    network_mode: 'host'
    stdin_open: true
    command: '--data-dir /data --api-key=typesense --enable-cors'
    volumes:
      - ./data:/data