all_4chan_boards = {
  "a": "Anime & Manga",
  "b": "Random",
  "c": "Anime/Cute",
  "d": "Hentai/Alternative",
  "e": "Ecchi",
  "f": "Flash",
  "g": "Technology",
  "gif": "Adult GIF",
  "h": "Hentai",
  "hr": "High Resolution",
  "k": "Weapons",
  "m": "Mecha",
  "o": "Auto",
  "p": "Photo",
  "r": "Adult Requests",
  "s": "Sexy Beautiful Women",
  "t": "Torrents",
  "u": "Yuri",
  "v": "Video Games",
  "vg": "Video Game Generals",
  "vm": "Video Games/Multiplayer",
  "vmg": "Video Games/Mobile",
  "vr": "Retro Games",
  "vrpg": "Video Games/RPG",
  "vst": "Video Games/Strategy",
  "w": "Anime/Wallpapers",
  "wg": "Wallpapers/General",
  "i": "Oekaki",
  "ic": "Artwork/Critique",
  "r9k": "ROBOT9001",
  "s4s": "Shit 4chan Says",
  "vip": "Very Important Posts",
  "qa": "Question & Answer",
  "cm": "Cute/Male",
  "hm": "Handsome Men",
  "lgbt": "LGBT",
  "y": "Yaoi",
  "3": "3DCG",
  "aco": "Adult Cartoons",
  "adv": "Advice",
  "an": "Animals & Nature",
  "bant": "International/Random",
  "biz": "Business & Finance",
  "cgl": "Cosplay & EGL",
  "ck": "Food & Cooking",
  "co": "Comics & Cartoons",
  "diy": "Do It Yourself",
  "fa": "Fashion",
  "fit": "Fitness",
  "gd": "Graphic Design",
  "hc": "Hardcore",
  "his": "History & Humanities",
  "int": "International",
  "jp": "Otaku Culture",
  "lit": "Literature",
  "mlp": "Pony",
  "mu": "Music",
  "n": "Transportation",
  "news": "Current News",
  "out": "Outdoors",
  "po": "Papercraft & Origami",
  "pol": "Politically Incorrect",
  "pw": "Professional Wrestling",
  "qst": "Quests",
  "sci": "Science & Math",
  "soc": "Cams & Meetups",
  "sp": "Sports",
  "tg": "Traditional Games",
  "toy": "Toys",
  "trv": "Travel",
  "tv": "Television & Film",
  "vp": "Pokemon",
  "vt": "Virtual YouTubers",
  "wsg": "Worksafe GIF",
  "wsr": "Worksafe Requests",
  "x": "Paranormal",
  "xs": "Extreme Sports",
}