services:
  lnx:
    image: chillfish8/lnx:0.9.0
    # image: chillfish8/lnx:latest
    network_mode: 'host'
    stdin_open: true
    environment:
      - AUTHORIZATION_KEY=hello
      - LOG_LEVEL=info
    volumes:
      - "./data:/etc/lnx/index"